// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Ol6LHx1FlmZTioeGBRkLoHtjMIZdQps',
    appId: '1:466494312425:web:7297843574919c7fa6c578',
    messagingSenderId: '466494312425',
    projectId: 'vapeshop-ecommerce',
    authDomain: 'vapeshop-ecommerce.firebaseapp.com',
    storageBucket: 'vapeshop-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4bbzM0xJl_C43Mvt2qMCRiawn-NcVXJU',
    appId: '1:466494312425:android:74c0f674b1ebf652a6c578',
    messagingSenderId: '466494312425',
    projectId: 'vapeshop-ecommerce',
    storageBucket: 'vapeshop-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJ5CcLG59v4cTN2k0CUe1-ajtgip1ZOQ',
    appId: '1:466494312425:ios:aafdb0416b715b92a6c578',
    messagingSenderId: '466494312425',
    projectId: 'vapeshop-ecommerce',
    storageBucket: 'vapeshop-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.vapeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJ5CcLG59v4cTN2k0CUe1-ajtgip1ZOQ',
    appId: '1:466494312425:ios:aafdb0416b715b92a6c578',
    messagingSenderId: '466494312425',
    projectId: 'vapeshop-ecommerce',
    storageBucket: 'vapeshop-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.vapeshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Ol6LHx1FlmZTioeGBRkLoHtjMIZdQps',
    appId: '1:466494312425:web:c8d64443c6f55619a6c578',
    messagingSenderId: '466494312425',
    projectId: 'vapeshop-ecommerce',
    authDomain: 'vapeshop-ecommerce.firebaseapp.com',
    storageBucket: 'vapeshop-ecommerce.firebasestorage.app',
  );
}
